### ISSUE TITLE
Materialize all fake tensor reference at once

### ISSUE THREAD

**Issue by YangFei1990** [pytorch/torchdistx#12]
**Is your feature request related to a problem? Please describe:**
When `deferred_init` is used all tensors created are fake tensors. Those tensors can be referred at different locations, but materialize one won't apply to all references. Check the example below.

**Describe the solution you would like:**
```
import torch
from torchdistx.deferred_init import deferred_init, materialize_module, materialize_tensor

m = deferred_init(torch.nn.Linear, 2, 2)
weight = m.weight
materialize_module(m)
print(weight) # --->still the fake tensor
```
It is better to have something like `to` or `cuda` operation
```
import torch
m = torch.nn.Linear(2,2)
weight = m.weight
m.to(torch.float16)
print(weight.dtype) #torch.float16
```
**Describe the alternatives you have considered:**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context:**
Add any other context about the feature request here.

**Comment by cbalioglu** [comment]
Thanks for the feedback @YangFei1990! Actually I had the same intention when I first started working on this feature, so I agree that an in-place materialization would be a cleaner approach. Unfortunately such behavior requires changes in the `TensorImpl` class in PyTorch to make it "fake aware". Since this is an out-of-core implementation, technically we don't have a way to do that. In case we port this feature into PyTorch at some point in the future, I will definitely re-consider your proposal.
